name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          wget https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.17.tar.gz
          tar xvf libiconv-1.17.tar.gz
          cd libiconv-1.17
          export CFLAGS='-ggdb -fsanitize=address'
          export LDFLAGS='-fsanitize=address'
          ./configure
          make

      - name: make check
        run: |
          export ASAN_OPTIONS="detect_leaks=0"
          cd libiconv-1.17
          make check
